/**
 * Copyright (c) 2017 European Organisation for Nuclear Research (CERN), All Rights Reserved.
 */

package cern.molr.commons.response;

/**
 * A response bean to an instantiation request containing mission ID generated by MolR server
 *
 * @author yassine-kr
 */
public class InstantiationResponseBean {

    private String missionExecutionId;

    public InstantiationResponseBean() {
    }

    public InstantiationResponseBean(String missionExecutionId) {
        this.missionExecutionId = missionExecutionId;
    }

    public String getMissionExecutionId() {
        return missionExecutionId;
    }

}
