package cern.molr.commons.response;

/**
 * Bean response to a register request containing the supervisor ID generated by the MolR server
 *
 * @author yassine-kr
 */
public class SupervisorRegisterResponseBean {

    private String supervisorId;

    public SupervisorRegisterResponseBean() {
    }

    public SupervisorRegisterResponseBean(String supervisorId) {
        this.supervisorId = supervisorId;
    }

    public String getSupervisorId() {
        return supervisorId;
    }

}
