/**
 * Copyright (c) 2017 European Organisation for Nuclear Research (CERN), All Rights Reserved.
 */

package cern.molr.client.api;

import cern.molr.commons.api.request.MissionCommand;
import cern.molr.commons.api.response.CommandResponse;
import cern.molr.commons.api.response.MissionEvent;
import cern.molr.commons.api.response.MissionState;
import org.reactivestreams.Publisher;

/**
 * Controller used to control a mission execution
 *
 * @author yassine-kr
 */
public interface ClientMissionController {

    /**
     * A method which gets the events stream generated by the mission execution
     *
     * @return a stream of events triggered by the mission execution
     */
    Publisher<MissionEvent> getEventsStream();

    /**
     * A method which gets the states stream generated by the mission execution
     *
     * @return a stream of states generated by the mission execution
     */
    Publisher<MissionState> getStatesStream();


    /**
     * A method which sends a {@link MissionCommand} in order to control the mission execution
     *
     * @param command the command to execute
     *
     * @return a stream of one element which tells whether the command was accepted or not
     */
    Publisher<CommandResponse> instruct(MissionCommand command);
}
