package cern.molr.commons.states;

import cern.molr.commons.api.request.MissionCommand;
import cern.molr.commons.api.response.MissionState;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A state generated by the MoleRunner
 *
 * @author yassine-kr
 */
public class MissionRunnerState extends MissionState {

    private final State state;

    public MissionRunnerState(@JsonProperty("level") Level level, @JsonProperty("status") String status,
                              @JsonProperty("possibleCommands") List<MissionCommand> possibleCommands, @JsonProperty
                                      ("state") State state) {
        super(level, status, possibleCommands);
        this.state = state;
    }

    public MissionRunnerState(String status, List<MissionCommand> possibleCommands, State state) {
        super(Level.MOLE_RUNNER, status, possibleCommands);
        this.state = state;
    }

    public State getState() {
        return state;
    }

    public enum State {
        NOT_YET_STARTED,
        MISSION_STARTED,
        MISSION_FINISHED,
        MISSION_ERROR,
        SESSION_TERMINATED
    }
}
