/**
 * Copyright (c) 2017 European Organisation for Nuclear Research (CERN), All Rights Reserved.
 */

package cern.molr.commons.api.response;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response bean to an instantiation request containing mission ID generated by MolR server
 *
 * @author yassine-kr
 */
public final class InstantiationResponseBean {

    private final String missionId;

    public InstantiationResponseBean(@JsonProperty("missionId") String missionId) {
        this.missionId = missionId;
    }

    public String getMissionId() {
        return missionId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstantiationResponseBean responseBean = (InstantiationResponseBean) o;

        return !(missionId != null ? !missionId.equals(responseBean.missionId) : responseBean.missionId != null);

    }

    @Override
    public int hashCode() {
        return missionId != null ? missionId.hashCode() : 0;
    }

}
