package cern.molr.commons.api.response;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Bean response containing the supervisor ID generated by the MolR server.
 *
 * @author yassine-kr
 */
public final class SupervisorRegisterResponseBean {

    private final String supervisorId;

    public SupervisorRegisterResponseBean(@JsonProperty("supervisorId") String supervisorId) {
        this.supervisorId = supervisorId;
    }

    public String getSupervisorId() {
        return supervisorId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SupervisorRegisterResponseBean responseBean = (SupervisorRegisterResponseBean) o;

        return !(supervisorId != null ? !supervisorId.equals(responseBean.supervisorId) : responseBean.supervisorId != null);

    }

    @Override
    public int hashCode() {
        return supervisorId != null ? supervisorId.hashCode() : 0;
    }

}
